apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Namespace }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8083