<<<<<<< HEAD
replicaCount: 1
image:
  repository: efranca/node-order-service
  tag: "592abe5"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3001
=======
replicaCount: 1

image:
  repository: 184239210367.dkr.ecr.us-east-1.amazonaws.com/node-order-service
  tag: "ec29225"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

>>>>>>> e665b4c (fix: fixing node-order-repo repo url)
