{
 "title": "Task-Api",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency - P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_requests_seconds_bucket{namespace=\"Task-Api\"}[5m]))by(le,uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"Task-Api\"}[5m]))by(uri,status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Mem Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})by(id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}