apiVersion: v1
kind: Service
metadata:
  name: {{ .chart.Name}}
  labels:
    app: {{ .chart.Name}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .chart.Name}}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}