replicaCount: 1
image:
  repository: 184239210367.dkr.ecr.us-east-1.amazonaws.com/node-shipping-service
  tag: "448f228"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3003
env:
  - name: SERVICE_NAME
    value: "node-shipping-service"
